version: '3.1'
services:
  db:
    container_name: linus_adm_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=linus
      - MYSQL_PASSWORD=linus123
      - MYSQL_DATABASE=linus
    volumes:
      - "../db_data/mysql:/var/lib/mysql"
    ports:
     - "3306:3306"